name: repro-collab
channels:
  - conda-forge
dependencies:
  # for R
  - r-base=4.2.3
  - r-rmarkdown=2.21
  - r-tidyverse=2.0.0
  - r-stargazer=5.2.3
  - r-languageserver=0.3.15 # vscode specific
  - r-httpgd=1.3.1 # vscode specific
  - radian=0.6.5 # vscode specific
  # other useful stuff
  - cmake=3.26.3
  - pandoc
  - tectonic=0.12.0
  # for python it would look like this
  # - python=3.11.3
  # - pip=23.1.2
  # - pip:
  #   - pandoc-include==1.2.0